const TERMS = [
  {
    term: 'Run Folder',
    definition:
      'A timestamped benchmark execution batch. It groups all summary rows produced during one benchmark campaign and acts as the primary scope boundary for single-run analysis.',
  },
  {
    term: 'Framework + Version',
    definition:
      'The technology variant under test, such as nextjs-v15.1.4. The version matters because benchmark behavior can change across releases even when the framework name stays the same.',
  },
  {
    term: 'Preset',
    definition:
      'The Lighthouse execution profile — typically mobile or desktop. Presets are not interchangeable because throttling, viewport size, and device assumptions affect the score landscape.',
  },
  {
    term: 'Route',
    definition:
      'The application page path that was benchmarked. Routes should only be compared against the same route because different pages load different amounts of content and logic.',
  },
  {
    term: 'Iteration',
    definition:
      'The repeated execution index for the same route / framework / preset tuple. Iterations capture natural variability and make distributions visible instead of relying on a single measurement.',
  },
  {
    term: 'Artifact',
    definition:
      'The raw JSON, HTML, or CSV report generated by Lighthouse for a single test row. Artifacts are the evidence layer behind the dashboard and are used to explain score changes and audit outcomes.',
  },
];

export default function WikiFrameworksPage() {
  return (
    <div className="space-y-5 min-w-0">
      {/* Header */}
      <section className="rounded-xl border border-white/8 bg-card p-5">
        <p className="text-[10px] uppercase tracking-[0.3em] text-cyan-300/60">Knowledge Base</p>
        <h1 className="mt-1.5 text-2xl font-semibold text-foreground">Framework and Benchmark Terms</h1>
        <p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">
          These terms define the data dimensions used in the dashboard filters, tables, and charts. A framework label
          alone is not enough for analysis — the version, platform preset, route, and iteration all affect the result.
        </p>
      </section>

      {/* Term cards */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {TERMS.map(({ term, definition }) => (
          <article key={term} className="rounded-xl border border-white/8 bg-card p-4">
            <p className="text-xs font-semibold text-foreground">{term}</p>
            <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{definition}</p>
          </article>
        ))}
      </div>

      {/* Interpretive rule */}
      <section className="rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-5">
        <h2 className="text-sm font-semibold text-cyan-100">Interpretive rule</h2>
        <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
          A valid comparison requires the same route, the same preset, and an adequate number of iterations. Framework
          conclusions based on mixed routes or mixed device profiles are not scientifically valid because they confound
          the independent variable with other sources of variation.
        </p>
      </section>
    </div>
  );
}
